In [ ]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/fagonzalezo/ai4eng-unal/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()

In [ ]:
from local.lib.rlxmoocapi import submit, session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L02.02", varname="student");

logging in as jpastor@unal.edu.co... please wait

-------------
using course session ai4eng.v1.unal::intro_si_2025_2
success!! you are logged in
-------------


In [ ]:
import numpy as np

Task 1

In [ ]:
import numpy as np

def cauchy(x, y):
    d = x.reshape(-1,1) - y
    if np.any(d == 0): raise ValueError("Division by zero in Cauchy matrix")
    return 1.0 / d

In [ ]:
x = np.array([45, 31, 67, 75, 54])
y = np.array([17,  7, 15, 15, 18])

print(cauchy(x,y))

[[0.03571429 0.02631579 0.03333333 0.03333333 0.03703704]
 [0.07142857 0.04166667 0.0625     0.0625     0.07692308]
 [0.02       0.01666667 0.01923077 0.01923077 0.02040816]
 [0.01724138 0.01470588 0.01666667 0.01666667 0.01754386]
 [0.02702703 0.0212766  0.02564103 0.02564103 0.02777778]]


In [ ]:
x = np.array([45, 31, 67, 75, 54])
y = np.array([17,  7, 15, 75, 18])
cauchy(x,y)

ValueError: Division by zero in Cauchy matrix

In [ ]:
t1_actual = cauchy(x,y)

ValueError: Division by zero in Cauchy matrix

In [ ]:
student.submit_task(globals(), task_id="task_01");

KeyError: 't1_actual'

Task 2


In [ ]:
import numpy as np

def minimo(x, v):
    return np.argmin(np.abs(x - v))

In [ ]:
x = np.arange(25,55,3)
v = 34

print(minimo(x,v))

In [ ]:
student.submit_task(globals(), task_id="task_02");

Task 3

In [ ]:
import numpy as np

def media(X):
    return X - X.mean(axis=1, keepdims=True)


In [ ]:
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(media(X))

In [ ]:
student.submit_task(globals(), task_id="task_03");

Task 4

In [ ]:
import numpy as np

def doublediag(X):
    return X + np.eye(X.shape[0]) * X

In [ ]:
X = np.array([[79, 45, 67,  8, 37],
              [47, 40,  5, 79, 86],
              [72, 25, 44, 45, 22],
              [12, 85,  8, 53, 28],
              [ 4, 37, 36, 40, 16]])

print(doublediag(X))

[[158.  45.  67.   8.  37.]
 [ 47.  80.   5.  79.  86.]
 [ 72.  25.  88.  45.  22.]
 [ 12.  85.   8. 106.  28.]
 [  4.  37.  36.  40.  32.]]


In [ ]:
student.submit_task(globals(), task_id="task_04");